config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :categories, only: :show
  get "workers/:id", to: "categories#worker", as: :worker
  resources :services, except: [:show, :index] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show] do
    resources :reviews, only: :create
  end

  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service
  has_many :reviews, through: :user
  has_one :review

  validates :start_date, :price, presence: true
  validates :price, numericality: { only_integer: true }
  validates_comparison_of :end_date, greater_than: :start_date
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    Booking.all.each { |booking| update_status(booking) }
    @worker_bookings = Booking.joins(:service).where(service: {user: current_user}).order(id: :desc)
    @customer_bookings = Booking.where(user: current_user).order(id: :desc)
  end

  def new
    @booking = Booking.new
    @booking.start_date = Time.now - (3600 * 4)
    @service = Service.find(params[:service_id])
  end

  def create
    @service = Service.find(params[:service_id])
    @booking = Booking.new(booking_params)
    @booking.end_date = @booking.start_date + (@service.duration * 60)
    @booking.service = @service
    @booking.user = current_user
    if @booking.save
      flash.notice = "Booking successfully created!"
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    update_status(@booking)
    if @booking.review.nil?
      @review = Review.new
    else
      @review = @booking.review
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :price, :status)
  end

  def update_status(booking)
    booking.end_date < (Time.now - (5 * 3600)).utc ? booking.update(status: true) : booking.update(status: false)
  end
end

app/views/bookings/_customer_list.html.erb
<% bookings.each do |booking| %>
  <% worker_name = "#{booking.service.user.first_name.capitalize} #{booking.service.user.last_name.capitalize}" %>
  <%= link_to booking_path(booking) do %>
    <div class="card-b booking-effect card-<%= booking.status %>">
        <div class="left-column work-<%= booking.status %>">
            <h6 class="T1"><%= worker_name.capitalize %></h6>
            <h2 class="T2 font_text">$<%= number_with_delimiter(booking.price, :delimiter => '.') %></h2>
          </div>
          <div class="right-column">
            <div>
              <h4 class=""><%= booking.service.name.capitalize %></h4>
              <h6 class="text-muted font_text"><%= booking.start_date.strftime('%d/%m/%y (%H:%M)') %> - <%= booking.end_date.strftime('%d/%m/%y (%H:%M)') %></h6>
            </div>
          </div>
      </div>
    <% end %>
<% end %>

app/views/bookings/_form.html.erb
<div class="container p-3">
  <h2 class="py-3">Book Service: <%= service.name %></h2>
  <%= simple_form_for [service, booking] do |f| %>
    <%= f.input :start_date, label: "Date", as: :datetime, html5: true, input_html: {min: Date.today} , hint: "duration: #{service.duration} minutes"%>
    <%= f.input :price, input_html: {value: service.price.to_i || 0}, readonly: true %>
    <%= f.submit "Submit Booking", class: "btn btn-success mt-3" %>
  <% end %>
</div>

app/views/bookings/_review.html.erb
<% if @booking.review.nil? && @booking.status && @booking.service.user != current_user %>
  <h2>Review</h2>
  <%= render "reviews/form", review: @review, booking: @booking %>
<% elsif @booking.review %>
  <h2>Review</h2>
  <div class="review-box">
      <div class="caja-top">
        <div class="perfil">
          <div class="perfil-i1">
            <%= cl_image_tag (@booking.user.photo.key || "user"), height: 140, width: 140, crop: :scale %>
          </div>
          <div class="name-user">
              <p class="mb-1"><strong class="font_title"><%= @booking.review.booking.user.first_name %></strong>&nbsp<%= @booking.review.created_at.strftime('(%d/%m/%y %H:%M)') %></p>
            </div>
        </div>
        <div class="reviews">
          <% @booking.review.rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        </div>
        </div>
        <div class="comments">
          <p><%= @booking.review.content %></p>
        </div>
      </div>
    </div>
<% end %>

app/views/bookings/_worker_list.html.erb
<% bookings.each do |booking| %>
  <% worker_name = "#{booking.service.user.first_name.capitalize} #{booking.service.user.last_name.capitalize}" %>
  <%= link_to booking_path(booking) do %>
    <div class="card-d booking-effect card-<%= booking.status %>">
      <div class="left-column work-<%= booking.status %>">
          <h6 class="T1"><%= worker_name %></h6>
          <h2 class="T2 font_text">$<%= number_with_delimiter(booking.price, :delimiter => '.') %></h2>
        </div>
        <div class="right-column">
          <div>
            <h4 class=""><%= booking.service.name.capitalize %></h4>
            <h6 class="text-muted font_text"><%= booking.start_date.strftime('%d/%m/%y (%H:%M)') %> - <%= booking.end_date.strftime('%d/%m/%y (%H:%M)') %></h6>
          </div>
        </div>
    </div>
  <% end %>
<% end %>

app/views/bookings/index.html.erb
<div class="container-b container">
  <div class="row">
    <div class="col-6 col-md-6 col-lg-6">
      <h3 class="title-C text-center">Customer Bookings</h3>
        <%= render "customer_list", bookings: @customer_bookings %>
    </div>
    <div class="col-6 col-md-6 col-lg-6">
      <h3 class="title-W text-center">Worker Bookings</h3>
        <%= render "worker_list", bookings: @worker_bookings %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<%= render "form", service: @service, booking: @booking %>

app/views/bookings/show.html.erb
<div class="container-rv">
  <div class="rvw">
    <div class="v position-relative">
      <strong><h1 class="text-center"><%= @booking.service.name.capitalize %></h1></strong>
      <h4>Start Time: <%= @booking.start_date.strftime('%d/%m/%y (%H:%M)') %></h4>
      <h4>End Time: <%= @booking.end_date.strftime('%d/%m/%y (%H:%M)') %></h4>
      <h4>Worker:&nbsp <%= link_to @booking.service.user.first_name.capitalize, worker_path(@booking.service.user) %></h4>
      <h4>Price: $<%= number_with_delimiter(@booking.price, :delimiter => '.') %></h4>
      <h4 class="mb-5 pe-3">Status:&nbsp<span class="fw-bold <%= @booking.status ? "text-success" : "text-warning" %>"><%= @booking.status ? " Done" : " Pending" %></span></h4>
      <%= link_to "Send a Message", chatroom_path(1), class: "btn btn-success btn-booking position-absolute bottom-0 end-0 me-4 btn-chat" %>
    </div>

    <%= render "bookings/review" %>

  </div>
</div>