config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :categories, only: :show
  get "workers/:id", to: "categories#worker", as: :worker
  resources :services, except: [:show, :index] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show] do
    resources :reviews, only: :create
  end

  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end

end

app/views/shared/_banner.html.erb
<div class="container-talenty-banner " >

  <div class="text-and-icon-talenty-banner">

    <div class="text-talenty-banner">
      <h1>Talenty</h1>
      <h3>Connecting home needs with human talent</h3>
      <div class="aliear-talenty">
        <p>Filter here the category you want to find, we are here to</p>
        <p>  facilitate your ideal employee</p>
      </div>

    </div>

    <div class="icon_logo_talenty_banner">
      <%= image_tag "icon2-talenty"%>
    </div>

  </div>



</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-talenty footer py-2">
  <div class="up-talenty" >
    <div class="icons-green">
      <%= image_tag "insta_footer.svg" %>
      <%= image_tag "insta_footer.svg" %>
      <%= image_tag "youtube_footer.svg" %>
      <%= image_tag "face_footer.svg" %>
    </div>
    <div class="titulo">
      <%= image_tag "talenty_footer.svg" %>
    </div>
    <div class="icons-green">
      <%= image_tag "link_footer.svg" %>
      <%= image_tag "insta_footer.svg" %>
      <%= image_tag "youtube_footer.svg" %>
    </div>
  </div>
  <div class="down-talenty" >
    <div>
        <%= image_tag "telefo_footer.svg" %>
        <%= image_tag "correo_footer.svg" %>
        <%= image_tag "localitation_footer.svg" %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
 <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand logo-talenty-nav-var" do %>
      <%= image_tag "icon-talenty-small" %><span class="ps-1 fst-italic">Talenty</span>
    <% end %>
    <button
      class="navbar-toggler  "
      type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent ">
      <ul class="navbar-nav me-auto ">
          <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My Profile", worker_path(current_user), class: "text-talenty-nav-var " %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", bookings_path, class: "text-talenty-nav-var" %>
          </li>
          <li class="nav-item dropdown">
            <%= cl_image_tag (current_user.photo.key || "user"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "login-a nav-link" %>
          </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>