config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :categories, only: :show
  get "workers/:id", to: "categories#worker", as: :worker
  resources :services, except: [:show, :index] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show] do
    resources :reviews, only: :create
  end

  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :services
  has_one_attached :photo
  has_many :users, through: :services

  validates :name, format: { with: /\A[a-zá-úA-ZÁ-ÚñÑ\s]*\z/, message: "only letters allowed" }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @category = Category.find_by(name: params[:id])
    @workers = @category.users.uniq
    @ratings = []
    @workers.each do |worker|
      reviews = worker.reviews
      @ratings << calculate_rating(reviews)
    end
  end

  def worker
    @worker = User.find(params[:id])
    @services = @worker.services
    @reviews = @worker.reviews
    @rating = calculate_rating(@reviews)
    @full_name = full_name(@worker)
  end

  private

  def calculate_rating(reviews)
    return 0 unless reviews.any?

    sum = 0
    reviews.each { |review| sum += review.rating}
    avg = sum / reviews.length
    return avg
  end

  def full_name(user)
    "#{user.first_name} #{user.last_name}"
  end
end

app/views/categories/_reviews.html.erb
<% if @worker.reviews.any? %>
<h3 class="ms-4">Reviews</h3>
<div class="container-reviews mb-5">


  <% @worker.reviews.each do |review| %>
    <div class="review-box">
      <div class="caja-top">
        <div class="perfil">
          <div class="perfil-i1">
            <%= cl_image_tag (review.booking.user.photo.key || "user") %>
          </div>
            <div class="name-user">
              <p class="m-0"><strong class="font_title"><%= review.booking.user.first_name %></strong>&nbsp<%= review.created_at.strftime('(%d/%m/%y %H:%M)') %></p>
              <p class="m-0 font_title"><%= review.booking.service.name %></p>
            </div>
        </div>
        <div class="reviews">
          <% review.rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
        </div>
      </div>
      <div class="comments">
        <p><%= review.content.capitalize %></p>
      </div>
    </div>
  <% end %>

</div>
<% end %>

app/views/categories/_services.html.erb
<div class="container1 position-relative mb-4">
  <h3>Services</h3>
  <% if @worker == current_user %>
    <%= link_to "+ Add Service", new_service_path, class: "bt1 position-absolute top-0 end-0" %>
  <% end %>
  <ul class="list-group mt-4 border border-3 rounded">
    <% @worker.services.each do |service| %>
      <% if @worker == current_user %>
          <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-action py-3 bg-light.bg-gradient">
          <div class="me-auto ">
            <%= link_to service.name.capitalize, edit_service_path(service), class: "link-full ps-2 text-secondary" %>
          </div>
          <%= link_to service_path(service), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"link-inside" do %>
            <i class="fa-solid fa-trash-can"></i>
          <% end %>
          </li>
      <% else %>
      <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-action py-4 bg-light.bg-gradient">
        <div class="me-auto ">
        <%= link_to service.name.capitalize, new_service_booking_path(service), class: "link-full ps-2 text-secondary" %>
        </div>
        <i class="fa-solid fa-arrow-right-to-bracket pe-1"></i>
        <i class="fa-solid fa-book"></i>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/categories/_workers_list.html.erb
<% @workers.each_with_index do |worker, index| %>
  <% name = "#{worker.first_name.capitalize} #{worker.last_name.capitalize}" %>
  <div class="outer-div">
    <%= link_to worker_path(worker) do %>
      <div class="inner-div">
        <div class="front">
          <div class="front__face-photo" style="background-image: url('<%= cl_image_path (worker.photo.key || "user"), height: 300, crop: :fill %>')"></div>
          <div class="front__text">
              <h3 class="front__text-header"><%= name %></h3>
              <p class="front__text-para m-0">
                <div class="reviews">
                  <% @ratings[index].times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                </div>
              </p>
          </div>
        </div>
        <div class="back px-1">
          <div class="social-media-wrapper">
            <h3>Info</h3>
            <ul class="no-style-list">
              <li><h5 class="font_text">Address: <%= worker.address %></h5></li>
              <li><h5 class="font_text">Phone: <%= worker.phone %></h5></li>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/categories/show.html.erb
<div class= "container">
  <h1><%= @category.name %></h1>
  <div class="cards mb-3">
    <%= render "workers_list" %>
  </div>
</div>

app/views/categories/worker.html.erb
<div class="container">
  <div class="sombra">
    <div class= "avatar-perfil" style="background-image: url('<%= cl_image_path (@worker.photo.key || "user"), height: 140, width: 140, crop: :scale %>')"></div>
    <div class="datos-perfil">
        <h4 class="titulo-usuario"><%= @full_name %></h4>
        <p class="bio-usuario m-0"><%= @worker.address %></p>
        <div class= "star-widget">
          <% @rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% if @rating == 0 %>
            <i class="fas fa-star invisible"></i>
          <% end %>
        </div>
    </div>
  </div>

  <div class="row col-12 ps-4">
    <div class="col-12 col-lg-6 prof p-3">
      <h2 class="my-4">
        <strong class="font_title"> Work Profile</strong>
      </h2>
      <p class="p-4"><%= @worker.description %></p>
    </div>
    <div class="col-12 col-lg-6">
      <div class="row">
      <% if @worker.photos_services.attached? %>
        <% @worker.photos_services.each do |photo| %>
          <div class="col-6">
            <img src="<%= cl_image_path (photo.key)%>" alt="" class="photo">
          </div>
        <% end %>
      <% else %>
        <div class="d-flex m-1">
          <div class="col-12 col-lg-6">
            <img src="https://img.freepik.com/vector-premium/carpintero-su-lugar-trabajo-herramientas-trabajo_313242-616.jpg?w=996" alt="photo1" class="photo">

            <img src="https://img.freepik.com/vector-premium/carpintero-su-lugar-trabajo-herramientas-trabajo_313242-616.jpg?w=996" alt="photo2" class="photo">
          </div>
          <div class="col-12 col-lg-6">
            <img src="https://img.freepik.com/vector-premium/carpintero-su-lugar-trabajo-herramientas-trabajo_313242-616.jpg?w=996" alt="photo3" class="photo">

              <img src="https://img.freepik.com/vector-premium/carpintero-su-lugar-trabajo-herramientas-trabajo_313242-616.jpg?w=996" alt="photo4" class="photo">
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
  <%= render "services" %>
  <%= render "reviews" %>
</div>