config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :categories, only: :show
  get "workers/:id", to: "categories#worker", as: :worker
  resources :services, except: [:show, :index] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show] do
    resources :reviews, only: :create
  end

  resources :chatrooms, only: [:show, :create] do
    resources :messages, only: :create
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.user = @booking.service.user
    @review.booking = @booking
    if @review.save
      redirect_to booking_path(@booking)
    else
      @booking.review = nil
      flash.alert = "Invalid Review"
      render "bookings/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/views/reviews/_form.html.erb
<%= simple_form_for [booking, review], url: booking_reviews_path(booking), class: "position-relative" do |f| %>
  <%= f.input :rating, collection: (1..5).to_a, label: false, input_html: {data: {controller: "star-rating"}}, class: "position-absolute top-0 start-100" %>
  <div class="textarea-review">
    <%= f.input :content, label: false %>
  </div>
  <div class="btn-review">
    <%= f.submit "Submit review", class: "btn-submit" %>
  </div>
<% end %>